services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak

    ports:
      - "8080:8080"

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth
      KC_PROXY: edge
      KC_HOSTNAME_URL: https://16.171.10.56.sslip.io/auth
      KC_HOSTNAME_ADMIN_URL: https://16.171.10.56.sslip.io/auth
      KC_HOSTNAME_STRICT_HTTPS: "true"

    volumes:
      - ./themes:/opt/keycloak/themes
      - ./realms:/opt/keycloak/data/import

    command:
      - start-dev
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
      - --import-realm
