export default [
  {id : "R01", nameFr : "Fond de roulement", nameAng : "Working Capital"}, 
  {id : "R02", nameFr : "Besoin en fond de roulement BFR", nameAng : "Working Capital Requirement"},
  {id : "R04", nameFr : "Trésorerie nette", nameAng : "Net Treasury"},
  {id : "R07", nameFr : "Capacité d'autofinancement", nameAng : "Self-Financing Capacity"},
  {id : "R05", nameFr : "Exédent brut d'exploitation", nameAng : "Gross Operating Surplus"},
  {id : "Rges", nameFr : "Ratio de gestion", nameAng : "Management Ratios"},
  {id : "R12", nameFr : "Recouvrement des comptes clients (durée des crédits clients)", nameAng : "Accounts Receivable Turnover"},
  {id : "R13", nameFr : "Taux de rotation des stocks de marchandises", nameAng : "Inventory Turnover - Goods"},
  {id : "R14", nameFr : "Renouvellement des stocks de marchandises", nameAng : "Stock Renewal - Goods"},
  {id : "R15", nameFr : "Taux de rotation des stocks de matières premières", nameAng : "Inventory Turnover - Raw Materials"},
  {id : "R16", nameFr : "Renouvellement des stocks de matières premières", nameAng : "Stock Renewal - Raw Materials"},
  {id : "R17", nameFr : "Taux de rotation des stocks de produits finis (calculer en interne)", nameAng : "Finished Goods Turnover"},
  {id : "R18", nameFr : "Renouvellement des stocks de produits finis (calculer en interne)", nameAng : "Finished Goods Renewal"},
  {id : "R19", nameFr : "Durée des crédits fournisseurs", nameAng : "Accounts Payable Duration"},
  {id : "R20", nameFr : "Taux de Rotation des immobilisations", nameAng : "Fixed Assets Turnover"},
  {id : "R21", nameFr : "Taux de Rotation des actifs", nameAng : "Asset Turnover Ratio"},
  {id : "R22", nameFr : "Cycle de conversion de l'encaisse", nameAng : "Cash Conversion Cycle"},
  {id : "R23", nameFr : "Ratio de croissance de la production", nameAng : "Production Growth Ratio"},
  {id : "R24", nameFr : "Ratio de croissance du CA HT", nameAng : "Net Sales Growth Ratio"},
  {id : "R25", nameFr : "Ratio de l'âge des immobilisations", nameAng : "Fixed Assets Age Ratio"},
  {id : "R26", nameFr : "Ratio du personnel", nameAng : "Staff Ratio"},
  {id : "R27", nameFr : "Taux de rotation du BFR", nameAng : "Working Capital Turnover Ratio"},
  {id : "Rind", nameFr : "Indépendant", nameAng : "Indépendant"},
  {id : "Rliq", nameFr : "Ratio de liquidité", nameAng : "Liquidity Ratios"},
  {id : "R03", nameFr : "Besoin en fond de roulement d'exploitation BFR", nameAng : "Operating Working Capital Requirement"},
  {id : "R08", nameFr : "Liquidité immédiate", nameAng : "Cash Ratio"},
  {id : "R09", nameFr : "Liquidité générale", nameAng : "Current Ratio"},
  {id : "R10", nameFr : "Liquidité réduite", nameAng : "Quick Ratio"},
  {id : "R11", nameFr : "Ratio de marge de trésorerie", nameAng : "Cash Margin Ratio"},
  {id : "Rend", nameFr : "Ratio d'endettement", nameAng : "Debt Ratios"},
  {id : "R30", nameFr : "Ratio d'endettement général", nameAng : "Debt to Equity Ratio"},
  {id : "R31", nameFr : "Ratio d'endettement net ou Gearing", nameAng : "Net Debt Ratio"},
  {id : "R32", nameFr : "Ratio de la capacité de remboursement des dettes", nameAng : "Debt Repayment Capacity"},
  {id : "R33", nameFr : "Ratio du coût d'endettement", nameAng : "Cost of Debt Ratio"},
  {id : "R34", nameFr : "Ratio de couvertures des intérêts", nameAng : "Interest Coverage Ratio"},
  {id : "Rsol", nameFr : "Ratios de solvabilité", nameAng : "Solvency Ratios"},
  {id : "R28", nameFr : "Ratio de couverture des capitaux investis ou ratio d'equilibre financier", nameAng : "Capital Coverage Ratio"},
  {id : "R29", nameFr : "Ratio de l'autonomie financière", nameAng : "Financial Autonomy Ratio"},
  {id : "Rren", nameFr : "Ratios de rentabilité", nameAng : "Profitability Ratios"},
  {id : "R35", nameFr : "Taux de Marge brute", nameAng : "Gross Margin"},
  {id : "R36", nameFr : "Taux de Marge nette", nameAng : "Net Profit Margin"},
  {id : "R37", nameFr : "Taux de Marge brute d'exploitation", nameAng : "Operating Gross Margin"},
  {id : "R38", nameFr : "Ratio de return on assets (ROA) ou rentabilité économique", nameAng : "Return on Assets"},
  {id : "R39", nameFr : "Ratio de return on equity (ROE) ou la rentabilité finanière", nameAng : "Return on Equity"},
  {id : "R40", nameFr : "Ratio de la rentabilité financière pour Actionnaires", nameAng : "Shareholders' Return Ratio"},
  {id : "ECBA", nameFr : "Bilan Actif", nameAng : "Balance Sheet Assets"},
  {id : "ECBP", nameFr : "Bilan Passif", nameAng : "Balance Sheet Liabilities"},
  {id : "ECPC", nameFr : "CPC", nameAng : "Income Statement"},
  {id : "ESG", nameFr : "ESG", nameAng : "ESG"},
  {id : "EC001", nameFr : "Actif", nameAng : "Asset"},
  {id : "EC002", nameFr : "Actif circulant", nameAng : "Current asset"},
  {id : "EC003", nameFr : "Actif immobilisé", nameAng : "Fixed assets ou Non-current assets"},
  {id : "EC004", nameFr : "Achats consommés de matières et fournitures", nameAng : "Consumed purchases of materials and supplies"},
  {id : "EC005", nameFr : "Achats revendus de marchandises", nameAng : "Purchases of goods resold as-is"},
  {id : "EC006", nameFr : "Autofinancement", nameAng : "Self-financing"},
  {id : "EC007", nameFr : "Autres charges d'exploitation", nameAng : "Other operating expenses"},
  {id : "EC008", nameFr : "Autres charges externes", nameAng : "External charges"},
  {id : "EC009", nameFr : "Autres charges financières", nameAng : "Other financial expenses"},
  {id : "EC010", nameFr : "Autres créances financières", nameAng : "Other financial receivables"},
  {id : "EC011", nameFr : "Autres créanciers", nameAng : "Other non-trade payables"},
  {id : "EC012", nameFr : "Autres débiteurs", nameAng : "Other non-trade receivables"},
  {id : "EC013", nameFr : "Autres dettes de financement", nameAng : "Other long-term financing liabilities"},
  {id : "EC014", nameFr : "Autres immobilisations corporelles", nameAng : "Other tangible fixed assets"},
  {id : "EC015", nameFr : "Autres immobilisations incorporelles", nameAng : "Other intangible fixed assets"},
  {id : "EC016", nameFr : "Autres produits d'exploitation", nameAng : "Other operating income (miscellaneous)"},
  {id : "EC017", nameFr : "Autres provisions pour risques et charges momentanées", nameAng : "Other temporary risk and expense provisions"},
  {id : "EC018", nameFr : "Autres réserves", nameAng : "Other reserves"},
  {id : "EC019", nameFr : "Autres titres immobilisés", nameAng : "Other non-credit investment securities"},
  {id : "EC020", nameFr : "Banques solde débiteur", nameAng : "Bank accounts with debit balances"},
  {id : "EC021", nameFr : "Banques (soldes créditeurs)", nameAng : "Bank overdrafts / credit balances"},
  {id : "EC022", nameFr : "Brevets, marques, droits et valeurs similaires", nameAng : "Patents, trademarks and similar rights"},
  {id : "EC023", nameFr : "Caisses, régies d'avances et accréditifs", nameAng : "Cash /checkout"},
  {id : "EC025", nameFr : "Capital social ou personnel", nameAng : "Capital"},
  {id : "EC026", nameFr : "Capitaux propres", nameAng : "Equity"},
  {id : "EC027", nameFr : "Capitaux propres assimilés", nameAng : "Quasi-equity"},
  {id : "EC028", nameFr : "Charges d'exploitation", nameAng : "Operating expenses"},
  {id : "EC029", nameFr : "Charges non courantes", nameAng : "Non-recurring expenses"},
  {id : "EC030", nameFr : "Charges à répartir sur plusieurs exercices", nameAng : "Deferred charges"},
  {id : "EC031", nameFr : "Charges d'intérêt", nameAng : "Interests"},
  {id : "EC032", nameFr : "Charges de personnel", nameAng : "Staff expenses"},
  {id : "EC033", nameFr : "Charges financières", nameAng : "Financial expenses"},
  {id : "EC034", nameFr : "Chèques et valeurs à encaisser", nameAng : "Checks and receivable instruments"},
  {id : "EC035", nameFr : "Chiffre d'affaires", nameAng : "Revenue"},
  {id : "EC036", nameFr : "Clients créditeurs, avances et acomptes", nameAng : "Advance payment"},
  {id : "EC037", nameFr : "Compte d'associé débiteur", nameAng : "Shareholder current account (debit)"},
  {id : "EC038", nameFr : "Compte de régularisation actif", nameAng : "Accrued asset account"},
  {id : "EC039", nameFr : "Comptes d'associés créditeur", nameAng : "Shareholder current account (credit)"},
  {id : "EC040", nameFr : "Comptes de régularisation – passif", nameAng : "Accrued liability account"},
  {id : "EC041", nameFr : "Constructions", nameAng : "Buildings and structural works"},
  {id : "EC042", nameFr : "Consommation de l'exercice", nameAng : "Period consumption"},
  {id : "EC043", nameFr : "Créances clients", nameAng : "Accounts receivable"},
  {id : "EC044", nameFr : "Crédits d'escompte", nameAng : "Discount credits"},
  {id : "EC045", nameFr : "Crédits de trésorerie", nameAng : "Treasury credits"},
  {id : "EC046", nameFr : "Dette de financement ou dette à long terme", nameAng : "Long-term liabilities"},
  {id : "EC047", nameFr : "Dividendes", nameAng : "Dividends"},
  {id : "EC048", nameFr : "Dotations d'exploitation", nameAng : "Operating depreciation and provisions"},
  {id : "EC049", nameFr : "Dotations financières", nameAng : "Financial depreciation and provisions"},
  {id : "EC050", nameFr : "Dotations non courantes", nameAng : "Non-current depreciation and provisions"},
  {id : "EC051", nameFr : "Écart de conversion actif (durable)", nameAng : "Foreign exchange loss (unrealized)"},
  {id : "EC052", nameFr : "Écart de conversion passif (durable)", nameAng : "Foreign exchange gain (unrealized)"},
  {id : "EC053", nameFr : "Écarts de réévaluation", nameAng : "Revaluation difference"},
  {id : "EC054", nameFr : "Emprunts obligataires", nameAng : "Bond borrowings"},
  {id : "EC056", nameFr : "État créditeur", nameAng : "Payables to the State"},
  {id : "EC057", nameFr : "État débiteur", nameAng : "Receivables from the State"},
  {id : "EC058", nameFr : "Excédent Brut d'exploitation", nameAng : "Earnings Before Interest"},
  {id : "EC059", nameFr : "Fonds commercial", nameAng : "Business goodwill"},
  {id : "EC060", nameFr : "Fournisseurs débiteurs, avances et acomptes", nameAng : "Supplier advances and receivables"},
  {id : "EC061", nameFr : "Fournisseurs et comptes rattachés", nameAng : "Suppliers"},
  {id : "EC062", nameFr : "Financement permanent", nameAng : "Permanent financing"},
  {id : "EC063", nameFr : "Frais préliminaires", nameAng : "Preliminary and incorporation expenses"},
  {id : "EC064", nameFr : "Gains de change", nameAng : "Foreign exchange gains"},
  {id : "EC065", nameFr : "Immobilisation en recherche et développement", nameAng : "Research and development assets"},
  {id : "EC066", nameFr : "Immobilisations corporelles", nameAng : "Tangible fixed asset"},
  {id : "EC067", nameFr : "Immobilisations corporelles en cours", nameAng : "Fixed assets under construction"},
  {id : "EC068", nameFr : "Immobilisations en non-valeur", nameAng : "Non-value asset"},
  {id : "EC069", nameFr : "Immobilisations financières", nameAng : "Financial fixed asset"},
  {id : "EC070", nameFr : "Immobilisations incorporelles", nameAng : "Intangible fixed asset"},
  {id : "EC071", nameFr : "Immobilisations produites par l'entreprise pour elle-même", nameAng : "Self-produced fixed assets"},
  {id : "EC072", nameFr : "Impôts et taxes", nameAng : "Taxes payable"},
  {id : "EC073", nameFr : "Impôts sur le résultat", nameAng : "Corporate income tax"},
  {id : "EC074", nameFr : "Installations techniques, matériel et outillage", nameAng : "Technical facilities, equipment and tools"},
  {id : "EC075", nameFr : "Intérêts et autres produits financiers", nameAng : "Interest and other financial income"},
  {id : "EC076", nameFr : "Marge brute sur vente en l'état", nameAng : "Gross Margin"},
  {id : "EC077", nameFr : "Marchandises", nameAng : "Stock of goods"},
  {id : "EC078", nameFr : "Matériel de transport", nameAng : "Transportation equipment"},
  {id : "EC079", nameFr : "Matières et fournitures consommables", nameAng : "Stock of raw materials"},
  {id : "EC080", nameFr : "Mobilier, matériel de bureau et aménagements", nameAng : "Office furniture, equipment and fittings"},
  {id : "EC081", nameFr : "Organismes sociaux", nameAng : "Social security and welfare institutions"},
  {id : "EC082", nameFr : "Passif (Bilan)", nameAng : "Liabilities"},
  {id : "EC083", nameFr : "Passif circulant", nameAng : "Current liabilities"},
  {id : "EC084", nameFr : "Perte de change", nameAng : "Foreign exchange losses"},
  {id : "EC085", nameFr : "Personnel débiteur", nameAng : "Staff receivable"},
  {id : "EC086", nameFr : "Personnel créditeur", nameAng : "Staff payable"},
  {id : "EC087", nameFr : "Prêts immobilisés", nameAng : "Long-term loans"},
  {id : "EC088", nameFr : "Primes d'émission, de fusion et d'apport", nameAng : "Issuance, merger and contribution premiums"},
  {id : "EC089", nameFr : "Primes de remboursement des obligations", nameAng : "Bond redemption premium"},
  {id : "EC090", nameFr : "Produits d'exploitation", nameAng : "Operating income"},
  {id : "EC091", nameFr : "Produits des cessions d'immobilisations", nameAng : "Asset disposal"},
  {id : "EC092", nameFr : "Produits des titres de participation et des autres titres immobilisés", nameAng : "Income from equity investments"},
  {id : "EC093", nameFr : "Produits financiers", nameAng : "Financial income"},
  {id : "EC094", nameFr : "Produits finis", nameAng : "Stock of finished goods"},
  {id : "EC095", nameFr : "Produits non courants", nameAng : "Non-recurring income"},
  {id : "EC096", nameFr : "Produits intermédiaires", nameAng : "Intermediate products"},
  {id : "EC097", nameFr : "Production de l'exercice", nameAng : "Production for the period"},
  {id : "EC098", nameFr : "Provisions durables pour risques et charges", nameAng : "Provisions for risks & charges"},
  {id : "EC099", nameFr : "Provisions réglementées", nameAng : "Regulated provisions"},
  {id : "EC100", nameFr : "Report à nouveau", nameAng : "Retained earnings"},
  {id : "EC101", nameFr : "Reprises d'exploitation", nameAng : "Operating write-backs"},
  {id : "EC102", nameFr : "Reprises financières", nameAng : "Financial reversals"},
  {id : "EC103", nameFr : "Reprises non courantes", nameAng : "Non-current reversals"},
  {id : "EC104", nameFr : "Réserve légale", nameAng : "Legal reserve"},
  {id : "EC105", nameFr : "Résultat d'exploitation", nameAng : "Operating income"},
  {id : "EC106", nameFr : "Résultat exceptionnel", nameAng : "Exceptional income"},
  {id : "EC107", nameFr : "Résultat financier", nameAng : "Financial income"},
  {id : "EC108", nameFr : "Résultat net", nameAng : "Net income"},
  {id : "EC109", nameFr : "Résultats nets en instance d'affectation", nameAng : "Net result pending allocation"},
  {id : "EC110", nameFr : "Subventions d'exploitation", nameAng : "Operating subsidy"},
  {id : "EC111", nameFr : "Subvention d'équilibre", nameAng : "Balance subsidy"},
  {id : "EC112", nameFr : "Subventions d'investissement", nameAng : "Investment subsidy"},
  {id : "EC113", nameFr : "Terrains", nameAng : "Land"},
  {id : "EC114", nameFr : "Titres de participation", nameAng : "Equity investments"},
  {id : "EC115", nameFr : "Titres et valeurs de placement", nameAng : "Marketable securities"},
  {id : "EC116", nameFr : "Trésorerie active", nameAng : "Cash and cash equivalents"},
  {id : "EC117", nameFr : "Trésorerie passive", nameAng : "Negative cash (overdraft)"},
  {id : "EC118", nameFr : "Valeur ajoutée", nameAng : "Added value"},
  {id : "EC119", nameFr : "Valeurs nettes d'amortissement", nameAng : "Net Book Value"},
  {id : "EC120", nameFr : "Variation de stocks de produits", nameAng : "Inventory change-finished goods and production"},
  {id : "EC121", nameFr : "Ventes de biens et services produits", nameAng : "Sales of goods and services produced"},
  {id : "EC122", nameFr : "Ventes de marchandises en l'état", nameAng : "Sales of goods in original condition"},
  {id : "EC123", nameFr : "Flux de trésorerie", nameAng : "Cash flow"},
  {id : "EC125", nameFr : "Stocks", nameAng : "Inventory"},
  {id : "EC126", nameFr : "Immobilisations Brutes", nameAng : "Gross fixed assets at acquisition cost"},
  {id : "EC127", nameFr : "Amortissements globaux", nameAng : "Depreciation"},
  {id : "EC128", nameFr : "Dettes du passif circulant", nameAng : "Current liabilities debts"},
  {id : "EC129", nameFr : "Endettement total", nameAng : "Total debt"},
  {id : "EC130", nameFr : "Endettement net", nameAng : "Net debt"},
  {id : "EC134", nameFr : "Résultat courant", nameAng : "Operating result before non-recurring items"},
  {id : "EC135", nameFr : "Subventions accordées", nameAng : "Granted subsidies"},
  {id : "EC136", nameFr : "Reprises sur subventions d'investissement", nameAng : "Reversals of investment grants"},
  {id : "EC137", nameFr : "Autres produits non courants", nameAng : "Other non-recurring income"},
  {id : "EC138", nameFr : "Autres charges non courantes", nameAng : "Other non-recurring expenses"},
  {id : "EC139", nameFr : "Résultat avant impôts", nameAng : "Result before tax"},
  {id : "EC141", nameFr : "Augmentation des créances immobilisées (en devises)", nameAng : "Increase in non-current receivables (foreign currency)"},
  {id : "EC142", nameFr : "Diminution des dettes de financement (en devises)", nameAng : "Decrease in financing liabilities (foreign currency)"},
  {id : "EC143", nameFr : "Provisions pour risques", nameAng : "Provisions for risks"},
  {id : "EC144", nameFr : "Provisions pour charges", nameAng : "Provisions for expenses"},
  {id : "EC145", nameFr : "Produits en cours", nameAng : "Work in progress / Production in progress"},
  {id : "EC146", nameFr : "Diminution des créances immobilisées", nameAng : "Decrease in non-current receivables (FX revaluation)"},
  {id : "EC147", nameFr : "Augmentation des dettes de financement", nameAng : "Increase in financing liabilities (FX revaluation)"},
  {id : "EC148", nameFr : "Comptes de liaison des établissements et succursales", nameAng : "Inter-branch accounts / Intercompany liaison accounts"},
  {id : "EC149", nameFr : "Amortissements des frais préliminaires", nameAng : "Depreciation of preliminary expenses"},
  {id : "EC150", nameFr : "Amortissements des charges à répartir", nameAng : "Depreciation of deferred charges"},
  {id : "EC151", nameFr : "Amortissements des primes de remboursement des obligations", nameAng : "Amortization and redemption premiums of bonds"},
  {id : "EC152", nameFr : "Amortissement de l'immobilisation en recherche et développement", nameAng : "Amortization of R&D assets"},
  {id : "EC153", nameFr : "Amortissement des brevets, marques, droits et valeurs similaires", nameAng : "Amortization of patents, trademarks, similar rights"},
  {id : "EC154", nameFr : "Amortissement du fonds commercial", nameAng : "Amortization of goodwill"},
  {id : "EC155", nameFr : "Amortissement des autres immobilisations incorporelles", nameAng : "Amortization of other intangible assets"},
  {id : "EC156", nameFr : "Amortissement des terrains", nameAng : "Depreciation of land"},
  {id : "EC157", nameFr : "Amortissement des autres constructions", nameAng : "Depreciation of other constructions"},
  {id : "EC158", nameFr : "Amortissement des installations techniques, matériels et outillage", nameAng : "Depreciation of technical installations, equipment and tooling"},
  {id : "EC159", nameFr : "Amortissement du matériel de transport", nameAng : "Depreciation of transportation equipment"},
  {id : "EC160", nameFr : "Amortissement du mobilier, matériel de bureau", nameAng : "Depreciation of furniture and office equipment"},
  {id : "EC161", nameFr : "Amortissement des autres immobilisations corporelles", nameAng : "Depreciation of other tangible fixed assets"},
  {id : "EC162", nameFr : "Provisions pour dépréciation des immobilisations incorporelles", nameAng : "Provisions for impairment of intangible assets"},
  {id : "EC163", nameFr : "Provisions pour dépréciation des immobilisations corporelles", nameAng : "Provisions for impairment of tangible assets"},
  {id : "EC164", nameFr : "Provisions pour dépréciation des prêts immobilisés", nameAng : "Provisions for impairment of fixed loans"},
  {id : "EC165", nameFr : "Provisions pour dépréciation des autres créances financières", nameAng : "Provisions for impairment of other financial receivables"},
  {id : "EC166", nameFr : "Provisions pour dépréciation des titres de participations", nameAng : "Provisions for impairment of equity investments"},
  {id : "EC167", nameFr : "Provisions pour dépréciation des autres titres immobilisés", nameAng : "Provisions for impairment of other fixed securities"},
  {id : "EC168", nameFr : "Provisions pour dépréciation des marchandises", nameAng : "Provisions for impairment of merchandise"},
  {id : "EC169", nameFr : "Provisions pour dépréciation des matières et fournitures", nameAng : "Provisions for impairment of raw materials and supplies"},
  {id : "EC170", nameFr : "Provisions pour dépréciation des produits en cours", nameAng : "Provisions for impairment of work-in-progress"},
  {id : "EC171", nameFr : "Provisions pour dépréciation des produits intermédiaires", nameAng : "Provisions for impairment of intermediate products"},
  {id : "EC172", nameFr : "Provisions pour dépréciation des produits finis", nameAng : "Provisions for impairment of finished goods"},
  {id : "EC173", nameFr : "Provisions pour dépréciation - fournisseurs débiteurs, avances et acomptes", nameAng : "Provisions for impairment of debit suppliers, advances and deposits"},
  {id : "EC174", nameFr : "Provisions pour dépréciation des clients et comptes rattachés", nameAng : "Provisions for impairment of customers and related accounts"},
  {id : "EC175", nameFr : "Provisions pour dépréciation du personnel - débiteur", nameAng : "Provisions for impairment of personnel debit"},
  {id : "EC176", nameFr : "Provisions pour dépréciation des comptes d'associés débiteurs", nameAng : "Provisions for impairment of debit accounts of associates"},
  {id : "EC177", nameFr : "Provisions pour dépréciation des autres débiteurs", nameAng : "Provisions for impairment of other debtors"},
  {id : "EC178", nameFr : "Provisions pour dépréciation des titres et valeur de placement", nameAng : "Provisions for impairment of securities and investments"},
  {id : "EC179", nameFr : "Provisions pour dépréciation des comptes de trésorerie", nameAng : "Provisions for impairment of cash accounts"},
  {id : "EC180", nameFr : "Achats de matières et fournitures des exercices antérieurs", nameAng : "Purchases of raw materials and supplies from previous periods"},
  {id : "EC181", nameFr : "Autres charges externes des exercices antérieurs", nameAng : "Other external charges from previous periods"},
  {id : "EC182", nameFr : "Impôts et taxes des exercices antérieurs", nameAng : "Taxes from previous periods"},
  {id : "EC183", nameFr : "Charges de personnel des exercices antérieurs", nameAng : "Personnel expenses from previous periods"},
  {id : "EC184", nameFr : "Autres charges d'exploitation des exercices antérieurs", nameAng : "Other operating charges from previous periods"},
  {id : "EC185", nameFr : "Dotations d'exploitation des exercices antérieurs", nameAng : "Depreciation and provisions from previous periods"},
  {id : "EC186", nameFr : "Charges d'intérêt des exercices antérieurs", nameAng : "Interest charges from previous periods"},
  {id : "EC187", nameFr : "Pertes de change des exercices antérieurs", nameAng : "Exchange losses from previous periods"},
  {id : "EC188", nameFr : "Autres charges financières des exercices antérieurs", nameAng : "Other financial expenses from previous periods"},
  {id : "EC189", nameFr : "Dotations financières des exercices antérieurs", nameAng : "Financial provisions from previous periods"},
  {id : "EC190", nameFr : "Valeurs nettes d'amortissement des immobilisations cédées des exercices antérieurs", nameAng : "Net book value of disposed assets from previous periods"},
  {id : "EC191", nameFr : "Subventions accordées des exercices antérieurs", nameAng : "Subsidies granted from previous periods"},
  {id : "EC192", nameFr : "Autres charges non courantes des exercices antérieurs", nameAng : "Other non-current expenses from previous periods"},
  {id : "EC193", nameFr : "Dotations non courantes des exercices antérieurs", nameAng : "Non-current provisions from previous periods"},
  {id : "EC194", nameFr : "Ventes de marchandises des exercices antérieurs", nameAng : "Sales of goods from previous periods"},
  {id : "EC195", nameFr : "Ventes de biens et services produits des exercices antérieurs", nameAng : "Sales of goods and services from previous periods"},
  {id : "EC196", nameFr : "Immobilisations produites des exercices antérieurs", nameAng : "Self-constructed assets from previous periods"},
  {id : "EC197", nameFr : "Subventions d'exploitation reçues des exercices antérieurs", nameAng : "Operating subsidies received from previous periods"},
  {id : "EC198", nameFr : "Autres produits d'exploitation des exercices antérieurs", nameAng : "Other operating income from previous periods"},
  {id : "EC199", nameFr : "Reprises sur amortissements et provisions des exercices antérieurs", nameAng : "Write-backs of depreciation and provisions from previous periods"},
  {id : "EC200", nameFr : "Produits des titres de participation et des autres titres immobilisés des exercices antérieurs", nameAng : "Income from equity and other long-term securities from previous periods"},
  {id : "EC201", nameFr : "Gains de change des exercices antérieurs", nameAng : "Exchange gains from previous periods"},
  {id : "EC202", nameFr : "Intérêts et autres produits financiers des exercices antérieurs", nameAng : "Interest and other financial income from previous periods"},
  {id : "EC203", nameFr : "Reprises sur dotations financières des exercices antérieurs", nameAng : "Write-backs of financial provisions from previous periods"},
  {id : "EC204", nameFr : "Produits des cessions des immobilisations des exercices antérieurs", nameAng : "Proceeds from disposals of fixed assets from previous periods"},
  {id : "EC205", nameFr : "Subventions d'équilibre reçues des exercices antérieurs", nameAng : "Equilibrium subsidies received from previous periods"},
  {id : "EC206", nameFr : "Reprises sur subventions d'investissement des exercices antérieurs", nameAng : "Write-backs of investment subsidies from previous periods"},
  {id : "EC207", nameFr : "Autres produits non courants des exercices antérieurs", nameAng : "Other non-recurring income from previous periods"},
  {id : "EC208", nameFr : "Reprises non courantes des exercices antérieurs", nameAng : "Other non-recurring write-backs from previous periods"},
  {id : "EC209", nameFr : "Écart de conversion actif (éléments circulants)", nameAng : "Foreign exchange loss (unrealized)"},
  {id : "EC210", nameFr : "Écart de conversion passif (éléments circulants)", nameAng : "Foreign exchange gain (unrealized)"},
  {id : "EC211", nameFr : "Achats revendus de marchandises des exercices antérieurs", nameAng : "Resold purchases from prior periods"},
  {id : "EC212", nameFr : "Actionnaires, Capital souscrit non appelé", nameAng : "Shareholders – Subscribed capital not called"},
  {id : "EC213", nameFr : "Immobilisations nettes", nameAng : "Net fixed assets / Net book value"},
  {id : "EC214", nameFr : "Ventes de marchandises en l'état totales", nameAng : "Sales of goods in original state"},
  {id : "EC215", nameFr : "Ventes de biens et services produits totales", nameAng : "Sales of manufactured goods and services"},
  {id : "EC216", nameFr : "Immobilisations produites par l'entreprise pour elle-même totales", nameAng : "Self-produced fixed assets"},
  {id : "EC217", nameFr : "Subventions d'exploitation totale", nameAng : "Operating grants"},
  {id : "EC218", nameFr : "Autres produits d'exploitation totaux", nameAng : "Other operating income"},
  {id : "EC219", nameFr : "Reprises d'exploitation totales", nameAng : "Operating reversals"},
  {id : "EC220", nameFr : "Achats revendus de marchandises totaux", nameAng : "Resold merchandise purchases"},
  {id : "EC221", nameFr : "Achats consommés de matières et fournitures totaux", nameAng : "Consumed raw materials and supplies"},
  {id : "EC222", nameFr : "Autres charges externes totales", nameAng : "Other external expenses"},
  {id : "EC223", nameFr : "Impôts et taxes totaux", nameAng : "Taxes and duties"},
  {id : "EC224", nameFr : "Charges de personnel totales", nameAng : "Personnel expenses"},
  {id : "EC225", nameFr : "Autres charges d'exploitation totales", nameAng : "Other operating expenses"},
  {id : "EC226", nameFr : "Dotation d'exploitation totale", nameAng : "Operating allowances"},
  {id : "EC227", nameFr : "Produits des titres de participation et des autres titres immobilisés totaux", nameAng : "Income from equity and other long-term securities"},
  {id : "EC228", nameFr : "Gains de change totaux", nameAng : "Foreign exchange gains"},
  {id : "EC229", nameFr : "Intérêts et autres produits financiers totaux", nameAng : "Interest and other financial income"},
  {id : "EC230", nameFr : "Reprises financières totales", nameAng : "Financial reversals"},
  {id : "EC231", nameFr : "Charges d'intérêt totales", nameAng : "Interest expenses"},
  {id : "EC232", nameFr : "Pertes de change totales", nameAng : "Foreign exchange losses"},
  {id : "EC233", nameFr : "Autres charges financières totales", nameAng : "Other financial expenses"},
  {id : "EC234", nameFr : "Dotations financières totales", nameAng : "Financial allowances"},
  {id : "EC235", nameFr : "Produits des cessions des immobilisations totaux", nameAng : "Disposal proceeds of fixed assets"},
  {id : "EC236", nameFr : "Subventions d'équilibre totales", nameAng : "Operating balance subsidies"},
  {id : "EC237", nameFr : "Reprises sur subventions d'investissement totales", nameAng : "Reversals of investment subsidies"},
  {id : "EC238", nameFr : "Autres produits non courants totaux", nameAng : "Other non-current income"},
  {id : "EC239", nameFr : "Reprises non courantes totales", nameAng : "Non-current reversals"},
  {id : "EC240", nameFr : "Valeurs nettes comptables des immobilisations cédées totales", nameAng : "Net book value of disposed assets"},
  {id : "EC241", nameFr : "Subventions accordées totales", nameAng : "Granted subsidies"},
  {id : "EC242", nameFr : "Autres charges non courantes totale", nameAng : "Other non-current expenses"},
  {id : "EC243", nameFr : "Dotations non courantes aux amortissements et provisions totales", nameAng : "Non-current amortizations and provisions"},
  {id : "EC244", nameFr : "Immobilisations en non valeur nettes", nameAng : "Deferred charges and non-value assets"},
  {id : "EC245", nameFr : "Immobilisations incorporelles nettes", nameAng : "Net intangible assets"},
  {id : "EC246", nameFr : "Immobilisations corporelles nettes", nameAng : "Net tangible fixed assets"},
  {id : "EC247", nameFr : "Immobilisations financières nettes", nameAng : "Net financial fixed assets"},
  {id : "EC248", nameFr : "Stocks nets", nameAng : "Net inventories"},
  {id : "EC249", nameFr : "Créances de l'actif circulant nettes", nameAng : "Net current receivables"},
  {id : "EC250", nameFr : "Titres et valeurs de placement nets", nameAng : "Net marketable securities"},
  {id : "EC251", nameFr : "Amortissements des immobilisations en non valeur", nameAng : "Depreciation of non-value assets"},
  {id : "EC252", nameFr : "Amortissements et provisions des immobilisations incorporelles", nameAng : "Depreciation and provisions on intangible assets"},
  {id : "EC253", nameFr : "Amortissements et provisions des immobilisations corporelles", nameAng : "Depreciation and provisions on tangible assets"},
  {id : "EC254", nameFr : "Provisions des immobilisations financières", nameAng : "Provisions on financial fixed assets"},
  {id : "EC255", nameFr : "Provisions pour dépréciation des stocks", nameAng : "Inventory impairment provisions"},
  {id : "EC256", nameFr : "Provisions pour dépréciation des créances de l'actif circulant", nameAng : "Current receivables impairment provisions"},
  {id : "EC257", nameFr : "Trésorerie active nette", nameAng : "Net active cash"},
  {id : "EC258", nameFr : "Créances de l'actif circulant brutes", nameAng : "Gross current receivables"}
]